// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCh0pdf3IJRgDBO7x5VIvVrRmSzc9O2XA',
    appId: '1:306058417663:web:4847dcbf078dc22ef743ca',
    messagingSenderId: '306058417663',
    projectId: 'cariunpam-d19b7',
    authDomain: 'cariunpam-d19b7.firebaseapp.com',
    storageBucket: 'cariunpam-d19b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYOZvui01gpJDQ8PWasDwTf65hSHjcXOQ',
    appId: '1:306058417663:android:ef5dae8d1678af93f743ca',
    messagingSenderId: '306058417663',
    projectId: 'cariunpam-d19b7',
    storageBucket: 'cariunpam-d19b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWlpNoBDYkRYgoQCKsp1_kmuk0J8EO5tU',
    appId: '1:306058417663:ios:09284392b4a201e9f743ca',
    messagingSenderId: '306058417663',
    projectId: 'cariunpam-d19b7',
    storageBucket: 'cariunpam-d19b7.firebasestorage.app',
    iosClientId: '306058417663-lpk8rb0kfi39qut1s7bs1ljjhkpm2cgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.cariunpam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWlpNoBDYkRYgoQCKsp1_kmuk0J8EO5tU',
    appId: '1:306058417663:ios:09284392b4a201e9f743ca',
    messagingSenderId: '306058417663',
    projectId: 'cariunpam-d19b7',
    storageBucket: 'cariunpam-d19b7.firebasestorage.app',
    iosClientId: '306058417663-lpk8rb0kfi39qut1s7bs1ljjhkpm2cgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.cariunpam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCh0pdf3IJRgDBO7x5VIvVrRmSzc9O2XA',
    appId: '1:306058417663:web:a90d78a660295330f743ca',
    messagingSenderId: '306058417663',
    projectId: 'cariunpam-d19b7',
    authDomain: 'cariunpam-d19b7.firebaseapp.com',
    storageBucket: 'cariunpam-d19b7.firebasestorage.app',
  );
}
